version: "3"
services:
  redis:
    container_name: yammo-redis
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    command: redis-server --requirepass yammo
    volumes:
      - "$PWD/dockerdata/redis:/data/redis"
