version: "3"
services:
  redis:
    container_name: yammo-redis
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - ${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - "$PWD/dockerdata/redis:/data/redis"

  mongodb:
    container_name: yammo-mongodb
    image: mongo:4.2.8
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    expose:
      - ${MONGO_PORT}
    command: mongod --port ${MONGO_PORT}
    volumes:
      - "$PWD/dockerdata/mongodb:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
